//========= Copyright TOKI, All rights reserved. ==============================//
//
// Purpose: Maplabs achievements.
//
//=============================================================================//
#include "cbase.h"

#ifdef CLIENT_DLL
#include "achievementmgr.h"
#include "baseachievement.h"

// Create achievement manager object
CAchievementMgr AchievementMgr;

class CAchievementMaplabMenu : public CBaseAchievement
{
protected:

	void Init()
	{
		SetFlags(ACH_SAVE_GLOBAL);
		m_bStoreProgressInSteam = true;
		SetGoal(1);
	}

	// Listen for this event (event must be defined in :/resource/modevents.res)
	virtual void ListenForEvents()
	{
		ListenForGameEvent("joined_ml");
	}

	void FireGameEvent_Internal(IGameEvent *event)
	{
		if (0 == Q_strcmp(event->GetName(), "joined_ml"))
		{
			IncrementCount();
		}
	}
};
DECLARE_ACHIEVEMENT(CAchievementMaplabMenu, ACHIEVEMENT_EVENT_JOIN_ML, "JOIN_ML", 5); // chris renamed the achievement in steamworks without telling me :(

// C stands for component. used to differentiate between achievements and their respective component.

class CAchievementMaplab01Completed : public CBaseAchievement
{
	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CMAPLAB01_1", "CMAPLAB01_2", "CMAPLAB01_3", "CMAPLAB01_4",
			"CMAPLAB01_5", "CMAPLAB01_6", "CMAPLAB01_7", "CMAPLAB01_8"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CMAPLAB01");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}

	// don't show progress notifications for this achievement, it's distracting
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementMaplab01Completed, ACHIEVEMENT_EVENT_MAPLAB01_ALL, "MAPLAB01_ALL", 5);

class CAchievementTesttube01Completed : public CBaseAchievement
{
	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CTESTTUBE01_1", "CTESTTUBE01_2", "CTESTTUBE01_3", "CTESTTUBE01_4",
			"CTESTTUBE01_5", "CTESTTUBE01_6", "CTESTTUBE01_7", "CTESTTUBE01_8",
			"CTESTTUBE01_10", "CTESTTUBE01_11", "CTESTTUBE01_12", "CTESTTUBE01_13",
			"CTESTTUBE01_14", "CTESTTUBE01_15", "CTESTTUBE01_16"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CTESTTUBE01");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}

	// don't show progress notifications for this achievement, it's distracting
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementTesttube01Completed, ACHIEVEMENT_EVENT_TESTTUBE01_ALL, "TESTTUBE01_ALL", 5);

class CAchievementMaplab02Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CMAPLAB02_1", "CMAPLAB02_2", "CMAPLAB02_3", "CMAPLAB02_4",
			"CMAPLAB02_5", "CMAPLAB02_6", "CMAPLAB02_7"

		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CMAPLAB02");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}

	// don't show progress notifications for this achievement, it's distracting
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementMaplab02Completed, ACHIEVEMENT_EVENT_MAPLAB02_ALL, "MAPLAB02_ALL", 5);

class CAchievementTesttube02Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CTESTTUBE02_1", "CTESTTUBE02_2", "CTESTTUBE02_3", "CTESTTUBE02_4",
			"CTESTTUBE02_5", "CTESTTUBE02_6", "CTESTTUBE02_7", "CTESTTUBE02_8"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CTESTTUBE02");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementTesttube02Completed, ACHIEVEMENT_EVENT_TESTTUBE02_ALL, "TESTTUBE02_ALL", 5);


class CAchievementMaplab03Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CMAPLAB03_1", "CMAPLAB03_2", "CMAPLAB03_3", "CMAPLAB03_4",
			"CMAPLAB03_5", "CMAPLAB03_6", "CMAPLAB03_7", "CMAPLAB03_8",
			"CMAPLAB03_9", "CMAPLAB03_10", "CMAPLAB03_11", "CMAPLAB03_12",
			"CMAPLAB03_13", "CMAPLAB03_14"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CMAPLAB03");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementMaplab03Completed, ACHIEVEMENT_EVENT_MAPLAB03_ALL, "MAPLAB03_ALL", 5);


class CAchievementTesttube03Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CTESTTUBE03_1", "CTESTTUBE03_2", "CTESTTUBE03_3", "CTESTTUBE03_4",
			"CTESTTUBE03_5", "CTESTTUBE03_6", "CTESTTUBE03_7", "CTESTTUBE03_8",
			"CTESTTUBE03_9", "CTESTTUBE03_10", "CTESTTUBE03_11", "CTESTTUBE03_12",
			"CTESTTUBE03_13", "CTESTTUBE03_14", "CTESTTUBE03_15", "CTESTTUBE03_16"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CTESTTUBE03");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementTesttube03Completed, ACHIEVEMENT_EVENT_TESTTUBE03_ALL, "TESTTUBE03_ALL", 5);

class CAchievementMaplab04Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CMAPLAB04_1", "CMAPLAB04_2", "CMAPLAB04_3", "CMAPLAB04_4",
			"CMAPLAB04_5", "CMAPLAB04_6", "CMAPLAB04_7", "CMAPLAB04_8",
			"CMAPLAB04_9", "CMAPLAB04_10", "CMAPLAB04_11"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CMAPLAB04");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementMaplab04Completed, ACHIEVEMENT_EVENT_MAPLAB04_ALL, "MAPLAB04_ALL", 5);

class CAchievementAtom01Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CATOM01_1", "CATOM01_2", "CATOM01_3", "CATOM01_4",
			"CATOM01_5", "CATOM01_6", "CATOM01_7", "CATOM01_8",
			"CATOM01_9", "CATOM01_10", "CATOM01_11", "CATOM01_12",
			"CATOM01_13", "CATOM01_14", "CATOM01_15"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CATOM01");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementAtom01Completed, ACHIEVEMENT_EVENT_ATOM01_ALL, "ATOM01_ALL", 5);

class CAchievementTesttube04Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CTESTTUBE04_1", "CTESTTUBE04_2", "CTESTTUBE04_3", "CTESTTUBE04_4",
			"CTESTTUBE04_5", "CTESTTUBE04_6", "CTESTTUBE04_7", "CTESTTUBE04_8",
			"CTESTTUBE04_9", "CTESTTUBE04_10", "CTESTTUBE04_11", "CTESTTUBE04_12",
			"CTESTTUBE04_13"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CTESTTUBE04");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementTesttube04Completed, ACHIEVEMENT_EVENT_TESTTUBE04_ALL, "TESTTUBE04_ALL", 5);

class CAchievementMaplab05Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CMAPLAB05_1", "CMAPLAB05_2", "CMAPLAB05_3", "CMAPLAB05_4",
			"CMAPLAB05_5", "CMAPLAB05_6", "CMAPLAB05_7", "CMAPLAB05_8",
			"CMAPLAB05_9", "CMAPLAB05_10", "CMAPLAB05_11", "CMAPLAB05_12",
			"CMAPLAB05_13", "CMAPLAB05_14", "CMAPLAB05_15", "CMAPLAB05_16",
			"CMAPLAB05_17", "CMAPLAB05_18", "CMAPLAB05_19", "CMAPLAB05_20",
			"CMAPLAB05_21", "CMAPLAB05_22", "CMAPLAB05_23", "CMAPLAB05_24"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CMAPLAB05");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementMaplab05Completed, ACHIEVEMENT_EVENT_MAPLAB05_ALL, "MAPLAB05_ALL", 5);


class CAchievementAtom02Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CATOM02_1", "CATOM02_2", "CATOM02_3", "CATOM02_4",
			"CATOM02_5", "CATOM02_6", "CATOM02_7", "CATOM02_8",
			"CATOM02_9", "CATOM02_10", "CATOM02_11", "CATOM02_12",
			"CATOM02_13", "CATOM02_14", "CATOM02_15"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CATOM02");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementAtom02Completed, ACHIEVEMENT_EVENT_ATOM02_ALL, "ATOM02_ALL", 5);

class CAchievementTesttube05Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CTESTTUBE05_1", "CTESTTUBE05_2", "CTESTTUBE05_3", "CTESTTUBE05_4",
			"CTESTTUBE05_5", "CTESTTUBE05_6", "CTESTTUBE05_7", "CTESTTUBE05_8",
			"CTESTTUBE05_9", "CTESTTUBE05_10", "CTESTTUBE05_11", "CTESTTUBE05_12",
			"CTESTTUBE05_13", "CTESTTUBE05_14", "CTESTTUBE05_15", "CTESTTUBE05_16"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CTESTTUBE05");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementTesttube05Completed, ACHIEVEMENT_EVENT_TESTTUBE05_ALL, "TESTTUBE05_ALL", 5);

class CAchievementMaplab06Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CMAPLAB06_1", "CMAPLAB06_2", "CMAPLAB06_3", "CMAPLAB06_4",
			"CMAPLAB06_5", "CMAPLAB06_6", "CMAPLAB06_7", "CMAPLAB06_8",
			"CMAPLAB06_9", "CMAPLAB06_10"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CMAPLAB06");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementMaplab06Completed, ACHIEVEMENT_EVENT_MAPLAB06_ALL, "MAPLAB06_ALL", 5);

class CAchievementTesttube06Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CTESTTUBE06_1", "CTESTTUBE06_2", "CTESTTUBE06_3", "CTESTTUBE06_4",
			"CTESTTUBE06_5", "CTESTTUBE06_6"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CTESTTUBE06");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementTesttube06Completed, ACHIEVEMENT_EVENT_TESTTUBE06_ALL, "TESTTUBE06_ALL", 5);

class CAchievementAtom03Completed : public CBaseAchievement
{

	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CATOM03_1", "CATOM03_2", "CATOM03_3", "CATOM03_4",
			"CATOM03_5", "CATOM03_6", "CATOM03_7", "CATOM03_8",
			"CATOM03_9", "CATOM03_10", "CATOM03_11"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CATOM03");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementAtom03Completed, ACHIEVEMENT_EVENT_ATOM03_ALL, "ATOM03_ALL", 5);

class CAchievementMaplab07Completed : public CBaseAchievement
{
	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CMAPLAB07_1", "CMAPLAB07_2", "CMAPLAB07_3", "CMAPLAB07_4",
			"CMAPLAB07_5", "CMAPLAB07_6", "CMAPLAB07_7", "CMAPLAB07_8",
			"CMAPLAB07_9", "CMAPLAB07_10", "CMAPLAB07_11", "CMAPLAB07_12",
			"CMAPLAB07_13", "CMAPLAB07_14", "CMAPLAB07_15", "CMAPLAB07_16"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CMAPLAB07");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementMaplab07Completed, ACHIEVEMENT_EVENT_MAPLAB07_ALL, "MAPLAB07_ALL", 5);

class CAchievementTesttube07Completed : public CBaseAchievement
{
	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CTESTTUBE07_1", "CTESTTUBE07_2", "CTESTTUBE07_3", "CTESTTUBE07_4",
			"CTESTTUBE07_5", "CTESTTUBE07_6", "CTESTTUBE07_7", "CTESTTUBE07_8",
			"CTESTTUBE07_9", "CTESTTUBE07_10", "CTESTTUBE07_11", "CTESTTUBE07_12",
			"CTESTTUBE07_13", "CTESTTUBE07_14", "CTESTTUBE07_15", "CTESTTUBE07_16"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CTESTTUBE07");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementTesttube07Completed, ACHIEVEMENT_EVENT_TESTTUBE07_ALL, "TESTTUBE07_ALL", 5);

class CAchievementMaplab08Completed : public CBaseAchievement
{
	virtual void Init()
	{
		static const char *szComponents[]=
		{
			"CMAPLAB08_1", "CMAPLAB08_2", "CMAPLAB08_3", "CMAPLAB08_4",
			"CMAPLAB08_5", "CMAPLAB08_6", "CMAPLAB08_7", "CMAPLAB08_8",
			"CMAPLAB08_9", "CMAPLAB08_10", "CMAPLAB08_11", "CMAPLAB08_12"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CMAPLAB08");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementMaplab08Completed, ACHIEVEMENT_EVENT_MAPLAB08_ALL, "MAPLAB08_ALL", 5);

class CAchievementTesttube08Completed : public CBaseAchievement
{
	virtual void Init()
	{
		static const char *szComponents[] =
		{
			"CTESTTUBE08_1", "CTESTTUBE08_2", "CTESTTUBE08_3", "CTESTTUBE08_4",
			"CTESTTUBE08_5", "CTESTTUBE08_6", "CTESTTUBE08_7", "CTESTTUBE08_8",
			"CTESTTUBE08_9", "CTESTTUBE08_10", "CTESTTUBE08_11", "CTESTTUBE08_12",
			"CTESTTUBE08_13", "CTESTTUBE08_14", "CTESTTUBE08_15", "CTESTTUBE08_16",
			"CTESTTUBE08_17", "CTESTTUBE08_18", "CTESTTUBE08_19", "CTESTTUBE08_20",
			"CTESTTUBE08_21"
		};
		SetFlags(ACH_HAS_COMPONENTS | ACH_LISTEN_COMPONENT_EVENTS | ACH_SAVE_GLOBAL);
		m_pszComponentNames = szComponents;
		m_iNumComponents = ARRAYSIZE(szComponents);
		SetComponentPrefix("CTESTTUBE08");
		SetGoal(m_iNumComponents);
		SetHideUntilAchieved(false);
	}
	virtual bool ShouldShowProgressNotification() { return false; }
};
DECLARE_ACHIEVEMENT(CAchievementTesttube08Completed, ACHIEVEMENT_EVENT_TESTTUBE08_ALL, "TESTTUBE08_ALL", 5);



// map logic achievements
//
// DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_EXAMPLE, "EXAMPLE", 5);
//"DECLARE_MAP_EVENT_ACHIEVEMENT" is what declares what type the achievement is. In this case a map triggered one.
//"ACHIEVEMENT_EVENT_EXAMPLE" is the name of the achievement itself, needs to be defined in hl2orange.spa.h                                       
//"EXAMPLE" is what actually gets sent to steamworks. Keep in mind that ACHIEVEMENT_EVENT will get automatically filtered away.                                       
// So if you made it say "ACHIEVEMENT_EVENT_MAPLAB89_5" then only "MAPLAB89_5" would be sent to steamworks.
// The last number is apparently the Xbox 360 Gamer Score you would get rewarded for completing the achievement, completely useless but AFAIK required.
//
//
//
// halloween horror
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_MAPLAB01_1, "MAPLAB01_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_MAPLAB01_2, "MAPLAB01_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_MAPLAB01_3, "MAPLAB01_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_MAPLAB01_4, "MAPLAB01_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_MAPLAB01_5, "MAPLAB01_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_MAPLAB01_6, "MAPLAB01_6", 5); 
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_MAPLAB01_7, "MAPLAB01_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_MAPLAB01_8, "MAPLAB01_8", 5);
//
// one room
//
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_1, "TESTTUBE01_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_2, "TESTTUBE01_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_3, "TESTTUBE01_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_4, "TESTTUBE01_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_5, "TESTTUBE01_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_6, "TESTTUBE01_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_7, "TESTTUBE01_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_8, "TESTTUBE01_8", 5);
//DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_9, "TESTTUBE01_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_10, "TESTTUBE01_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_11, "TESTTUBE01_11", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_12, "TESTTUBE01_12", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_13, "TESTTUBE01_13", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_14, "TESTTUBE01_14", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_15, "TESTTUBE01_15", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_EVENT_TESTTUBE01_16, "TESTTUBE01_16", 5);
//
// episode one
//
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB02_1, "MAPLAB02_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB02_2, "MAPLAB02_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB02_3, "MAPLAB02_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB02_4, "MAPLAB02_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB02_5, "MAPLAB02_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB02_6, "MAPLAB02_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB02_7, "MAPLAB02_7", 5);
//
// companion piece
//
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE02_1, "TESTTUBE02_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE02_2, "TESTTUBE02_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE02_3, "TESTTUBE02_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE02_4, "TESTTUBE02_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE02_5, "TESTTUBE02_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE02_6, "TESTTUBE02_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE02_7, "TESTTUBE02_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE02_8, "TESTTUBE02_8", 5);
//
//
//
// runthinkshootliveville2
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_1, "MAPLAB03_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_2, "MAPLAB03_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_3, "MAPLAB03_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_4, "MAPLAB03_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_5, "MAPLAB03_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_6, "MAPLAB03_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_7, "MAPLAB03_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_8, "MAPLAB03_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_9, "MAPLAB03_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_10, "MAPLAB03_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_11, "MAPLAB03_11", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_12, "MAPLAB03_12", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_13, "MAPLAB03_13", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB03_14, "MAPLAB03_14", 5);
//
//
//
// abstraction
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_1, "TESTTUBE03_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_2, "TESTTUBE03_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_3, "TESTTUBE03_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_4, "TESTTUBE03_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_5, "TESTTUBE03_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_6, "TESTTUBE03_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_7, "TESTTUBE03_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_8, "TESTTUBE03_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_9, "TESTTUBE03_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_10, "TESTTUBE03_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_11, "TESTTUBE03_11", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_12, "TESTTUBE03_12", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_13, "TESTTUBE03_13", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_14, "TESTTUBE03_14", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_15, "TESTTUBE03_15", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE03_16, "TESTTUBE03_16", 5);
//
//
//
// Think Tank
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB04_1, "MAPLAB04_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB04_2, "MAPLAB04_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB04_3, "MAPLAB04_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB04_4, "MAPLAB04_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB04_5, "MAPLAB04_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB04_6, "MAPLAB04_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB04_7, "MAPLAB04_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB04_8, "MAPLAB04_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB04_9, "MAPLAB04_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB04_10, "MAPLAB04_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB04_11, "MAPLAB04_11", 5);
//
//
//
// Blade
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_1, "ATOM01_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_2, "ATOM01_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_3, "ATOM01_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_4, "ATOM01_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_5, "ATOM01_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_6, "ATOM01_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_7, "ATOM01_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_8, "ATOM01_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_9, "ATOM01_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_10, "ATOM01_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_11, "ATOM01_11", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_12, "ATOM01_12", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_13, "ATOM01_13", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_14, "ATOM01_14", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM01_15, "ATOM01_15", 5);
//
//
//
// 1,000,000,000 Units
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_1, "TESTTUBE04_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_2, "TESTTUBE04_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_3, "TESTTUBE04_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_4, "TESTTUBE04_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_5, "TESTTUBE04_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_6, "TESTTUBE04_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_7, "TESTTUBE04_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_8, "TESTTUBE04_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_9, "TESTTUBE04_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_10, "TESTTUBE04_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_11, "TESTTUBE04_11", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_12, "TESTTUBE04_12", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE04_13, "TESTTUBE04_13", 5);
//
//
//
// Abridged
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_1, "MAPLAB05_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_2, "MAPLAB05_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_3, "MAPLAB05_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_4, "MAPLAB05_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_5, "MAPLAB05_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_6, "MAPLAB05_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_7, "MAPLAB05_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_8, "MAPLAB05_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_9, "MAPLAB05_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_10, "MAPLAB05_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_11, "MAPLAB05_11", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_12, "MAPLAB05_12", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_13, "MAPLAB05_13", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_14, "MAPLAB05_14", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_15, "MAPLAB05_15", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_16, "MAPLAB05_16", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_17, "MAPLAB05_17", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_18, "MAPLAB05_18", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_19, "MAPLAB05_19", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_20, "MAPLAB05_20", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_21, "MAPLAB05_21", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_22, "MAPLAB05_22", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_23, "MAPLAB05_23", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB05_24, "MAPLAB05_24", 5);
//
//
//
// ABC...etc
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_1, "ATOM02_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_2, "ATOM02_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_3, "ATOM02_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_4, "ATOM02_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_5, "ATOM02_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_6, "ATOM02_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_7, "ATOM02_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_8, "ATOM02_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_9, "ATOM02_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_10, "ATOM02_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_11, "ATOM02_11", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_12, "ATOM02_12", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_13, "ATOM02_13", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_14, "ATOM02_14", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM02_15, "ATOM02_15", 5);
//
//
//
// Blockout
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_1, "TESTTUBE05_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_2, "TESTTUBE05_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_3, "TESTTUBE05_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_4, "TESTTUBE05_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_5, "TESTTUBE05_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_6, "TESTTUBE05_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_7, "TESTTUBE05_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_8, "TESTTUBE05_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_9, "TESTTUBE05_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_10, "TESTTUBE05_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_11, "TESTTUBE05_11", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_12, "TESTTUBE05_12", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_13, "TESTTUBE05_13", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_14, "TESTTUBE05_14", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_15, "TESTTUBE05_15", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE05_16, "TESTTUBE05_16", 5);
//
//
//
// Halloween Horror 2: The Darkness
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB06_1, "MAPLAB06_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB06_2, "MAPLAB06_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB06_3, "MAPLAB06_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB06_4, "MAPLAB06_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB06_5, "MAPLAB06_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB06_6, "MAPLAB06_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB06_7, "MAPLAB06_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB06_8, "MAPLAB06_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB06_9, "MAPLAB06_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB06_10, "MAPLAB06_10", 5);
//
//
//
// Smoke on the Water (Isn't that a song?)
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE06_1, "TESTTUBE06_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE06_2, "TESTTUBE06_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE06_3, "TESTTUBE06_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE06_4, "TESTTUBE06_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE06_5, "TESTTUBE06_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE06_6, "TESTTUBE06_6", 5);
//
//
//
// Gnome
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM03_1, "ATOM03_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM03_2, "ATOM03_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM03_3, "ATOM03_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM03_4, "ATOM03_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM03_5, "ATOM03_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM03_6, "ATOM03_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM03_7, "ATOM03_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM03_8, "ATOM03_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM03_9, "ATOM03_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM03_10, "ATOM03_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_ATOM03_11, "ATOM03_11", 5);
//
//
//
// The Grid
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_1, "MAPLAB07_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_2, "MAPLAB07_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_3, "MAPLAB07_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_4, "MAPLAB07_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_5, "MAPLAB07_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_6, "MAPLAB07_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_7, "MAPLAB07_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_8, "MAPLAB07_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_9, "MAPLAB07_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_10, "MAPLAB07_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_11, "MAPLAB07_11", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_12, "MAPLAB07_12", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_13, "MAPLAB07_13", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_14, "MAPLAB07_14", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_15, "MAPLAB07_15", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB07_16, "MAPLAB07_16", 5);
//
//
//
// CromulentVille2
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_1, "TESTTUBE07_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_2, "TESTTUBE07_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_3, "TESTTUBE07_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_4, "TESTTUBE07_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_5, "TESTTUBE07_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_6, "TESTTUBE07_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_7, "TESTTUBE07_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_8, "TESTTUBE07_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_9, "TESTTUBE07_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_10, "TESTTUBE07_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_11, "TESTTUBE07_11", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_12, "TESTTUBE07_12", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_13, "TESTTUBE07_13", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_14, "TESTTUBE07_14", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_15, "TESTTUBE07_15", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE07_16, "TESTTUBE07_16", 5);
/*
	Companion Piece 2 with ADVANCED COMMENTS	
*/
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB08_1, "MAPLAB08_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB08_2, "MAPLAB08_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB08_3, "MAPLAB08_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB08_4, "MAPLAB08_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB08_5, "MAPLAB08_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB08_6, "MAPLAB08_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB08_7, "MAPLAB08_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB08_8, "MAPLAB08_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB08_9, "MAPLAB08_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB08_10, "MAPLAB08_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB08_11, "MAPLAB08_11", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_MAPLAB08_12, "MAPLAB08_12", 5);
//
//
//
// Eye Candy
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_1, "TESTTUBE08_1", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_2, "TESTTUBE08_2", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_3, "TESTTUBE08_3", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_4, "TESTTUBE08_4", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_5, "TESTTUBE08_5", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_6, "TESTTUBE08_6", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_7, "TESTTUBE08_7", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_8, "TESTTUBE08_8", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_9, "TESTTUBE08_9", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_10, "TESTTUBE08_10", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_11, "TESTTUBE08_11", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_12, "TESTTUBE08_12", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_13, "TESTTUBE08_13", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_14, "TESTTUBE08_14", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_15, "TESTTUBE08_15", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_16, "TESTTUBE08_16", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_17, "TESTTUBE08_17", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_18, "TESTTUBE08_18", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_19, "TESTTUBE08_19", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_20, "TESTTUBE08_20", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_EVENT_TESTTUBE08_21, "TESTTUBE08_21", 5);
#endif MAPLAB