// ALL SKIP STATEMENTS THAT AFFECT THIS SHADER!!!
// defined $LIGHTING_PREVIEW && defined $FASTPATH && $LIGHTING_PREVIEW && $FASTPATH

#include "shaderlib/cshader.h"
class ssao_combine_vs30_Static_Index
{
public:
	ssao_combine_vs30_Static_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_ssao_combine_vs30 1


class ssao_combine_vs30_Dynamic_Index
{
public:
	ssao_combine_vs30_Dynamic_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_ssao_combine_vs30 1

